### ISSUE TITLE
`/regen` command

### ISSUE THREAD

**Issue by thehunmonkgroup** [llm-workflow-engine/llm-workflow-engine#151]
Would be nice to be able to use the `Regenerate response` as on the main website.

A `!regen` command would do this.

**Comment by mmabrouk** [comment]
Good idea! I wonder how they do it on the website, do they remake the same api call or is there something more to it

**Comment by thehunmonkgroup** [comment]
It's a POST request, here's the payload:

![2023-02-26_09-27](https://user-images.githubusercontent.com/43772/221416634-417f4baf-3e48-4e4e-a22c-9d5ade59e51c.png)

I *think* what's happening there is mostly a copy of submitting a new question, you're just re-submitting the original message with an `action` of `variant`.

**Comment by thehunmonkgroup** [comment]
Browser backend has been removed, I think this was better suited to that backend, so closing for now.
