### ISSUE TITLE
Now, how do contexts really work?

### ISSUE THREAD

**Issue by yalla** [llm-workflow-engine/llm-workflow-engine#299]
I am slightly confused by how contexts are supposed to work.

What I think it does:
* goes back to a a specific conversation listed in /history,
* and there, to a specific point in that conversation.

The /help command shows a pair of UUIDs as an exmaple, but that's not what shows up in the logs, what I see there is something like `## context 6:49`. 

Using that brings me back to that specific context in that chat, but it is a little... cumbersome? For example, when I check the history, I have one conversation listed as such:

```
7 2023-05-12 09:07: "Top 10 Hottest and Coldest German Summers" (1)
```
And I can retrieve the chat history simply with `/chat 7`. But the context itself is something entirely else, which is only available to me when I enable logs...

Is there an easy way - for example, from the chat history - to grab the context for that specific "checkpoint"?

Or am I on the completely wrong track here...

Perhaps it would be impossible to include this "context" in a specific chat history so that it can be easily retrieved later?

Thanks!

**Comment by thehunmonkgroup** [comment]
Contexts were originally conceived for the browser backend, I'm not even sure they work properly on the API backend.

I don't have a great plan to improve this yet. One thing I've considered is something like a `/message` command, and you'd pass it the ID of a message, and it would switch conversation (if necessary), and take you to that message. The remaining problem would be that the API conversation messages currently have no concept of a 'parent' message, which you'd need to properly manage the various branches of a conversation. Then there's the issue of how to display a conversation if it has multiple branches.

Another approach I considered is some kind of `/fork` command. You'd pass that a message ID, and it would make a copy of the conversation up to and including that message, then switch to it. Now you have an entirely new conversation to work with. Seems like a lot of duplication, though.

It would be great if somebody else could put some brainpower on this, it's not all that high on my priority list.

**Comment by yalla** [comment]
Hi there,

thanks for the explainer. I looked more deeply into it and at least I figured out how to go back to a specific conversation, simply by

1. Look up all chats using `/history`
2. Use `/switch` to go to that chat
3. Use `/chat` to get the history of this chat.

It kind of replicates from what I know from ChatGPT's Web UI and somehow seems to do the trick for me.

But your `/fork` proposal sound real neat, as this would be something not even available in ChatGPT's WebUI... I'm all for it as this would enable me to test 'scenarios'; I'm not even sure if that is feasible in the sense of 'Can I simply pass on a UUID identifying a specific checkpoint in a chat and create a new branch, while keeping all other branches?'. Awesome idea!

**Comment by thehunmonkgroup** [comment]
If you take the time to understand OpenAI's API 'chat' endpoint: https://platform.openai.com/docs/api-reference/chat

You'll see that doing these kinds of divergent conversations is trivial in terms of getting the API to do it. The challenge is managing all the different threads in a way that doesn't become a mess.

BTW, you can use `/chat` directly to see the history of a chat, without switching to it as the active chat -- that's why they are separate commands.

**Comment by yalla** [comment]
Uh-hu, so you pass on that `messages` array with all past conversations so far, it's not tracked in OpenAI's platform? SO entirely stateless and derives the current state from whatever you provide? OK, I see two things here...
1. When the chat is long, the requests grows ever longer
2. Yeah, it'd be need to be tracked in the application.

Hm, how can this be done... OK, assume:
1. A new column `parent_conversation_id` in table `conversation` (may be `NULL`, but must still be unique)
2. Every time someone calls `/fork`, we create a new conversation with `parent_conversation_id` set to the `conversation.id` id of the 'calling' conversation
3. When adding a new message to the chat, it's `message.conversation_id` is set to the new generated id.

So far for populating the data... the premise would be, that 'every conversation having no `parent_conversation_id` is the root of an independent tree. So then it all boils down to tree traversing and how to fetch (and perhaps cache) the trees as a Python structures, loading them from the DB at startup.

The chore will be displaying it kind of nicely in the TUI, [Ascii/Unicode Trees](https://py-trees.readthedocs.io/en/devel/visualisation.html#ascii-unicode-trees) kind of looks ok-ish...

The `/chat` command would need to be adapted so that it pay attention to the presence of a `parent_conversation_id` so that it doesn't stop when it reached the first node of the forked 'branch', but when it's present, switchted over to the other conversation.

**Comment by thehunmonkgroup** [comment]
Right, so, a sh*tload of work...

It's not something I'd be interested in working on right now, so it would need sponsorship or a high-quality PR.

**Comment by thehunmonkgroup** [comment]
With the removal of the browser backend, `/context` command has been removed.

It may appear again in the future, but right now it doesn't make any sense.
