### ISSUE TITLE
Any way to log in without GUI ?

### ISSUE THREAD

**Issue by erovinmo** [llm-workflow-engine/llm-workflow-engine#309]
Hi, first of all thanks for this project, I found it quite useful.

Here is the problem I am facing : I'm trying to setup this tool on an AWS instance, but it seems running `chatgpt install` is impossible due to the fact that the instance does not have a GUI.

Is there any workaround ?

**Comment by thehunmonkgroup** [comment]
Browser backend has been removed, so this issue is no longer necessasry.
