### ISSUE TITLE
No response from gpt4 models

### ISSUE THREAD

**Issue by blz777** [llm-workflow-engine/llm-workflow-engine#311]
**Describe the bug**
I get no response from the GPT-4 models (none of them). GPT-3.5 works correctly.
Trying to get an answer from GPT-4 via the official web interface works correctly.

**To Reproduce**
```
❯ chatgpt

                  Provide a prompt, or type /help or ? to list commands.

text-davinci-002-render-sha 1> /model model_name gpt-4
Set model_name to gpt-4

gpt-4 1> /session

 • Session information refreshed.  The session appears to be usable.

gpt-4 1> Are you there?



gpt-4 2>

gpt-4 2> /model model_name text-davinci-002-render-sha
Set model_name to text-davinci-002-render-sha

text-davinci-002-render-sha 2> Are you there?

Yes, I'm here! How can I assist you today?

text-davinci-002-render-sha 3>
```

**Expected behavior**
Get answer from GPT-4 models as well.

**Additional context**
I installed chatgpt-wrapper from the latest on master: 

* c7a57ed (HEAD -> main, origin/main, origin/HEAD) add function manager

chatgpt-wrapper version: 
```
❯ chatgpt --version
/opt/homebrew/bin/chatgpt version 0.12.1
```

**Comment by mountaineerbr** [comment]
Hey, you may disable streaming:

Jun 14, 2023
[Empty messages in streaming Chat Completions requests](https://status.openai.com/incidents/j1ww30rj5c88)
Resolved - Users of our Chat Completions API in streaming mode received completions that were erroneously empty. The problem was traced to a specific code deployment. We have fully resolved the issue with the deployment and operations are now normal.

<https://status.openai.com/>

**Comment by blz777** [comment]
@mountaineerbr Thank you! I already tried disabling streaming. Here is another attempt:
```
text-davinci-002-render-sha 12> /model model_name gpt-4-browsing
Set model_name to gpt-4-browsing

gpt-4-browsing 12> /stream

 • Streaming mode is now disabled.

gpt-4-browsing 12> test


gpt-4-browsing 13>
```

**Comment by thehunmonkgroup** [comment]
Sadly, the problem looks much worse than a transient OpenAI bug. I'll detail what I've discovered below, and up front say that I have no good ideas for a solution yet.

It appears, for GPT-4 requests only, that OpenAI has put some 'bot security' in place, from this company:  https://www.arkoselabs.com

Here's what a GPT-4 request appears like in the console output:

![2023-06-15_08-37](https://github.com/mmabrouk/chatgpt-wrapper/assets/43772/b6f5595b-da65-4e3b-b54c-8b64aaa3c4dc)

Now, let's compare what we're sending in the POST request for new chats:

![2023-06-15_08-38](https://github.com/mmabrouk/chatgpt-wrapper/assets/43772/8ea4f25e-62cc-4c32-afe0-a1dae5d568ec)

To what `chat.openai.com` is now sending:

![2023-06-15_08-43](https://github.com/mmabrouk/chatgpt-wrapper/assets/43772/8587b570-e16d-4863-94a1-1fd8ca1ef6a4)

You can see the addition of a new `arkose_token` in the official web app request. This token changes with every GPT-4 request, and is not available in the session information.

GPT-3.5-Turbo requests to not seem to require this token:

![2023-06-15_08-39](https://github.com/mmabrouk/chatgpt-wrapper/assets/43772/2e28cf72-60fd-42b8-af39-0694bd312a83)

You can see the difference in the network activity, here is a GPT-3.5-Turbo request:

![2023-06-15_09-20](https://github.com/mmabrouk/chatgpt-wrapper/assets/43772/3957fc7a-59d2-4bba-8dd4-5a45fc30051c)

And here is a GPT-4 request:

![2023-06-15_09-21](https://github.com/mmabrouk/chatgpt-wrapper/assets/43772/834ba462-9b51-4bb0-bc52-a53d43eea353)

As you can see in the GPT-4 request, there are extra requests being made before the submission, and my assumption is these are the new bot security on the front of GPT-4, which somehow collects the needed `arkose_token` that's needed to submit with the chat request.

Finally, I will say that there have already been several fixes to the browser backend to work around OpenAI's ever-increasing security measures, and it keeps getting harder to overcome them.

It's unlikely that I will spend any more time chasing this down, I've tried to provide a reasonable description of the problem space, and hopefully a community member will take the ball from here and submit a PR that can work around this issue. If not, the browser backend's days may be numbered...

**Comment by thehunmonkgroup** [comment]
This is a small step in the right direction:

```javascript
 function sendPostRequest() {
   const xhr = new XMLHttpRequest();
   const url = "https://tcr9i.chat.openai.com/v2/35536E1E-65B4-4D96-9D97-6ADB7EFF8147/api.js";
   xhr.open("POST", url, true);
   xhr.onreadystatechange = function () {
     if (xhr.readyState === 4 && xhr.status === 200) {
       const response = JSON.parse(xhr.responseText);
       console.log(response);
     }
   };
   xhr.send();
 }

 // Call the function to send the POST request
 sendPostRequest();
```

Basically, I think the workflow is to `POST` some data to that URL and get the `arkose_token` back, although there may be a few steps in between. That code above is not working, because I did not figure out exactly what content needs to be posted to the URL, and it's throwing an error.

Since their javascript code is all minimized, it's pretty hard to make sense of the exact workflow they're using to retrieve the token.

Perhaps somebody can look at the Arkose Labs documentation and figure it out. If we can replicate the workflow and get our hands on a token, I believe we can get GPT-4 working again.

**Comment by m1sta** [comment]
I suspect that a quick resolution to this will require a fallback to a headless browser. 'Bot security' will be more than just a nonce. I assume this issue means that no plugins can be used via chatgpt since plugins are only usable with gpt-4?

**Comment by thehunmonkgroup** [comment]
> I suspect that a quick resolution to this will require a fallback to a headless browser.

The browser backend *is* a headless browser.

This issue only affects the browser backend, not the API backend. For GPT-4 access via the API backend, you  need to have been granted GPT-4 access by OpenAI.

**Comment by WaleedSalahEldeen** [comment]
Still no updates?

**Comment by thehunmonkgroup** [comment]
@WaleedSalahEldeen as mentioned already:

> It's unlikely that I will spend any more time chasing this down, I've tried to provide a reasonable description of the problem space, and hopefully a community member will take the ball from here and submit a PR that can work around this issue. If not, the browser backend's days may be numbered...

**Comment by thehunmonkgroup** [comment]
Browser backend has been removed, so this issue is no longer necessary.
