### ISSUE TITLE
Failed to Read Response

### ISSUE THREAD

**Issue by realet68** [llm-workflow-engine/llm-workflow-engine#323]
**Describe the bug**
Hi. I have been working with chatgpt-wrapper and llm-workflow for several months now. Thank you for supporting this effort! I've created a Python app that allows the user to interact through a narrative, and I have found that the playwright backend to ChatGPT is providing the best results for my app (versus the OpenAI API). 

There's an issue related to failed read responses that began as an infrequent problem (say with 5% of ChatGPT responses) and has increased to nearly every time. Load on the OpenAI side does not appear to be a factor, as the problem replicates on different days/different times of day. 

Regardless of whether I use the Python API object or the CLI, results are the same. Here is a sample from the CLI exactly as it appears in the session: 

(new_0317) C:\Users\reale\Envs>chatgpt
Provide a prompt for ChatGPT, or type !help or ? to list commands.
1> hello

Hello! How can I assist you today?Failed to read response from ChatGPT.  Tips:
 * Try again.  ChatGPT can be flaky.
 * Use the `session` command to refresh your session, and then try again.
 * Restart the program in the `install` mode and make sure you are logged in.

Sometimes [as above] I receive the entire response with the error message appended, sometimes I receive part of the response (as compared to what shows in the ChatGPT interface) with the error message appended, and sometimes I receive only the error message (although the ChatGPT web interface shows the completion successfully within the conversation). 

I have tried this on every point rev of the release code from 0.3.14 through 0.6.6. Each time I created a new virtual environment and installed dependencies from scratch. I am currently attempting to install an environment with the latest release, but the install for the readline dependency is giving me fits. (I'm working through it.)

I am running on Windows 11. I also acquired a linux machine and ported my code there, and was able to replicate the problem successfully. 

I have created this problem under Python 3.10.6 and 3.10.9. 

**To Reproduce**
Steps to reproduce the behavior: Create a fresh virtual environment and install chatgpt with any of the versions above. Perform playwright install firefox and chatgpt install. Open the CLI and begin chatting. 

**Expected behavior**
A clear and concise description of what you expected to happen: Chat completions that mirror exactly what is reflected in the ChatGPT web interface. 

**Additional context**
Add any other context about the problem here. Thanks for your help in advance!

**Comment by thehunmonkgroup** [comment]
The browser backend was removed in the lastest release: https://github.com/llm-workflow-engine/llm-workflow-engine/releases/tag/v0.15.0

You can see a brief explanation of why here: https://github.com/llm-workflow-engine/llm-workflow-engine/blob/main/CHATGPT_WRAPPER.md

I would be *very* surprised if you could not get as high quality answers from the API as you are from the ChatGPT app -- with the API you have full control over the system message, temperature, top_p, top_k, etc. I encourage you to play around with those!

FYI, this was the issue that really killed the browser backend for good: #311 -- despite me providing ample information in that issue, not a single person stepped forward to assist further with overcoming it, and I wasn't interested in it being a one-man show... ;)

**Comment by realet68** [comment]
Thanks for the quick response! The individual completions from the API are
just as good as anything generated within ChatGPT. However the
conversations within the site maintain context for much longer.

With the OpenAI API, I've written two apps. One can maintain contextual
references for about 400-600 words. The second can do twice that. Within
ChatGPT, completions are accurate and can refer back to anything mentioned
prior in the conversation for thousands of words.

I would be happy to work with you to see if there's a solution for this
problem. I did make some progress in decreasing the frequency of the
behavior by adding some TCP timeout settings within the Python app, and
adding a lock that kills the browser process after every completion also
increases stability a bit, but that's a hack at best.

Alternatively, if you have a method for getting the API to maintain
referential integrity as well as the site-based app can, I could rebuild my
app around that.

Thank you!

Tom

**Comment by thehunmonkgroup** [comment]
> Thanks for the quick response! The individual completions from the API are just as good as anything generated within ChatGPT. However the conversations within the site maintain context for much longer.

I gotta tell ya, this makes no sense to me. I've routinely had very long conversations via the API, and it's perfectly capable of maintaining the context of the conversation -- I recently had a GPT-4 conversation that was just over 8,000 tokens, and the limit is 8192. That worked perfectly.

If you're using GPT-4 models, then #311 is the issue.

But, for me, that ship has sailed. Perhaps somebody will fork the last 0.14.x release and revive the browser backend in another project.

**Comment by realet68** [comment]
I'll give it a shot, Thanks! I would MUCH rather pay the API rates anyway
so if it can work that would be great. I will note that I've only used
through the Davinci models so perhaps GPT-4 is remembering context better.
Appreciate the help!  -Tom

**Comment by thehunmonkgroup** [comment]
If you're going to work w/ the API, you really should be aware of the model sizes and capabilities: https://platform.openai.com/docs/models/overview

And be aware of GPT-4 availability: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4
