### ISSUE TITLE
How to change default model?

### ISSUE THREAD

**Issue by austinweisgrau** [llm-workflow-engine/llm-workflow-engine#327]
I've read through the documentation and don't see where it's described how to accomplish this.

I'd like to use gpt-4 by default.

I know that if I open a lwe interactive session, I can change the model for that session with `/config model gpt-4`. However, the change does not persist outside the session.

**Comment by thehunmonkgroup** [comment]
https://llm-workflow-engine.readthedocs.io/en/latest/model_access.html

**Comment by austinweisgrau** [comment]
Those instructions work to change the model for a single session but do not persist beyond a session - as I described in my original post.

**Comment by thehunmonkgroup** [comment]
I don't think you're reading the instructions carefully enough -- there's an entire section on setting a default preset.
