### ISSUE TITLE
OpenAI SDK update to v1.x breaks LWE

### ISSUE THREAD

**Issue by lantrix** [llm-workflow-engine/llm-workflow-engine#329]
**Describe the bug**

Out of the box install and any new conversation just won't work

```
[New Conversation]
(0.7/16384/0): default
ted@gpt-3.5-turbo-1106 1> Tell me something

AttributeError("module 'openai' has no attribute 'error'")
```

**To Reproduce**

- Install as per https://llm-workflow-engine.readthedocs.io/en/latest/installation.html
- Configure as per https://llm-workflow-engine.readthedocs.io/en/latest/configuration.html

**Expected behavior**

I can have a conversation with the default LLM

**Additional context**

It looks like OpenAI Python completely revamped their SDK last week
- Release https://github.com/openai/openai-python/releases/tag/v1.0.0
- Discussion https://github.com/openai/openai-python/discussions/742

**Comment by thehunmonkgroup** [comment]
There are a lot of breaking changes in the new `openai` library, it may take a bit to upgrade LWE to be compatible with it.

For now, I've pushed a fix to lock the `openai` package version to the last legacy release.

If you reinstall, it should work now.

I'll try to get a release rolled soon with the upgrades to the 1.x lib.

**Comment by thehunmonkgroup** [comment]
https://github.com/llm-workflow-engine/llm-workflow-engine/releases/tag/v0.18.3
