### ISSUE TITLE
/examples not found in path when I try to install examples (on windows)

### ISSUE THREAD

**Issue by Charlescad** [llm-workflow-engine/llm-workflow-engine#330]
Bug description: 
After install I run
`/examples`

`Are you sure you want to install examples for the following types? presets, templates, workflows, functions (y/n): y
Installing examples for: presets

[WinError 3] The system cannot find the path specified: 'C:\\Users\\charlescad\\AppData\\Local\\anaconda3-032023\\lib\\site-packages\\examples/presets'`

**Comment by Charlescad** [comment]
I cloned the repository and installed examples.

**Comment by thehunmonkgroup** [comment]
That path to the presets directory seems wrong. I'd need to see the output of `/config files` to help any further.

**Comment by thehunmonkgroup** [comment]
Ah, figured out the issue, examples dir was not included in the package version, this has been fixed in https://github.com/llm-workflow-engine/llm-workflow-engine/releases/tag/v0.18.4

Thanks for the report!
