### ISSUE TITLE
lwe config leads to error

### ISSUE THREAD

**Issue by dune73** [llm-workflow-engine/llm-workflow-engine#332]
**Describe the bug**
I get the following error when running the config.

```bash
Using legacy config directory: /home/user1/.config/chatgpt-wrapper

To dismiss this warning, move your configuration to the new default directory: 
/home/user1/.config/llm-workflow-engine

Using legacy data directory: /home/user1/.local/share/chatgpt-wrapper

To dismiss this warning, move your data to the new default directory: 
/home/user1/.local/share/llm-workflow-engine

Using legacy config directory: /home/user1/.config/chatgpt-wrapper

To dismiss this warning, move your configuration to the new default directory: 
/home/user1/.config/llm-workflow-engine

Using legacy data directory: /home/user1/.local/share/chatgpt-wrapper

To dismiss this warning, move your data to the new default directory: 
/home/user1/.local/share/llm-workflow-engine

Traceback (most recent call last):
  File "/home/user1/.local/bin/lwe", line 8, in <module>
    sys.exit(main())
  File "/home/user1/.local/lib/python3.10/site-packages/lwe/main.py", line 171, in main
    raise RuntimeError(f"Unknown backend: {backend}")
RuntimeError: Unknown backend: chatgpt-api

```

**To Reproduce**

```bash
$ pip install chatgpt-api
...
$ echo $?
0
$ pip install git+https://github.com/llm-workflow-engine/llm-workflow-engine
...
$ echo $?
0
$ lwe config
RuntimeError: Unknown backend: chatgpt-api
```

**Expected behavior**

I have not seen a successful execution of the command.

**Additional context**

I used the former wrapper version before.

**Comment by dune73** [comment]
Got it working myself, but you may still want to get rid of this bug for positive XP of other users.

**Comment by thehunmonkgroup** [comment]
> pip install chatgpt-api

This is a completely different project.

> RuntimeError: Unknown backend: chatgpt-api

Changed this to a warning message instead of RuntimeError.

**Comment by dune73** [comment]
When I ran lwe the first time, I got that error and thought it might be a dependency that slipped the attention. I think it must be due to me carrying over the old configuration from last Spring.

**Comment by thehunmonkgroup** [comment]
`chatgpt-api` was removed long ago, during the transition to the new branding.

**Comment by dune73** [comment]
I got this - and I do not want to pester you. But when calling the up to date version of `lwe`, `lwe` found a legacy config and started to inquire about `chatgpt-api` despite that dependency being removed long time ago.

If that's an edge case, you do not want to pursue, that's perfectly OK. I just want to make sure we're on the same page.

**Comment by thehunmonkgroup** [comment]
https://github.com/llm-workflow-engine/llm-workflow-engine/commit/be8a583102559277790ec0d521550ff63ce28585 addressed the inconsistency you reported.

**Comment by dune73** [comment]
Thank you.
