### ISSUE TITLE
ERROR: Invalid pattern is specified in "path:pattern"

### ISSUE THREAD

**Issue by johnd0e** [llm-workflow-engine/llm-workflow-engine#337]
**Describe the bug**
Getting this error when launching `/config edit` command in lwe.

**To Reproduce**
`set editor=C:\Apps\Far3\far.exe /e`

**Expected behavior**
I am expecting that when `editor` is set - it's value will be used as is.
There is no need to make any manipulation with `where`: if specified editor is in path in order to launch it there is no need to know full path to it.

**Additional context**
Windows 10

**Comment by thehunmonkgroup** [comment]
I need the full stack trace for the error, please.

> There is no need to make any manipulation with where

I don't understand this comment, please clarify.

**Comment by johnd0e** [comment]
> I need the full stack trace for the error, please.

It is not exception, thus there is no stack.

I can only provide what I can see in terminal.
For debug purposes I `set EDITOR=cmd.exe /c echo`.
Then in `lwe` I launch `/config edit`.
And see this:
<details>

```
                                                          Provide a prompt, or type /help or ? to list commands.

[New Conversation]
(0.7/16384/0): default
johnd0e@gpt-3.5-turbo-1106 1> /config edit
ERROR: Invalid argument or option - '/c'.
Type "WHERE /?" for usage help.
UnboundLocalError("cannot access local variable 'editor_paths' where it is not associated with a value")
[New Conversation]
(0.7/16384/0): default
johnd0e@gpt-3.5-turbo-1106 1>
```
</details>

> I don't understand this comment, please clarify

As you can see at my terminal "screenshot", the content of EDITOR variable is passed then to `where` command.
And (predictable) failed.

**Comment by thehunmonkgroup** [comment]
Run LWE in debug mode, that will provide more context:

`lwe -d`

**Comment by johnd0e** [comment]
```
                                                          Provide a prompt, or type /help or ? to list commands.

[New Conversation]
(0.7/16384/0): default
johnd0e@gpt-3.5-turbo-1106 1> /config edit
ERROR: Invalid argument or option - '/c'.
Type "WHERE /?" for usage help.
UnboundLocalError("cannot access local variable 'editor_paths' where it is not associated with a value")
Traceback (most recent call last):
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\core\repl.py", line 1410, in run_command
    response = method(obj, argument)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\core\repl.py", line 1350, in command_config
    file_editor(self.config.config_file)
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\core\editor.py", line 56, in file_editor
    command_parts = discover_editor()
                    ^^^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\core\editor.py", line 41, in discover_editor
    if editor_paths:
       ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'editor_paths' where it is not associated with a value
[New Conversation]
(0.7/16384/0): default
johnd0e@gpt-3.5-turbo-1106 1>
```

**Comment by thehunmonkgroup** [comment]
So here is the problem line:

```python
subprocess.check_output(f"where {editor}", shell=True).decode().strip()
```

Not being a Windows user, I have no idea why you're setting your `EDITOR` variable the way you are, with an argument -- never seen that on Linux. Typically on Linux, you wouldn't set arguments directly in `EDITOR`, instead you'd make a wrapper script that uses all the arguments, and set `EDITOR` to the wrapper script.

However, the editor path checking code should still support a fully specified path in `EDITOR`. Try the changes in this branch: https://github.com/llm-workflow-engine/llm-workflow-engine/tree/windows-editor-discovery

Keep in mind that those changes will NOT support `EDITOR` settings that contain arguments -- IMO that's bad practice, and you should be using the wrapper script approach I mentioned above to pass args if you really want to.

**Comment by johnd0e** [comment]
> Keep in mind that those changes will NOT support EDITOR settings that contain arguments -- IMO that's bad practice

Well, I'm not aware about any EDITOR practices, I was just blindly following documentation's wording, to the best of my understanding.

> https://github.com/llm-workflow-engine/llm-workflow-engine/tree/windows-editor-discovery

`set EDITOR="C:\Users\johnd0e\AppData\Local\Programs\Microsoft VS Code\Code.exe"`
And I see the same issue:
```
johnd0e@gpt-3.5-turbo 1> /config edit
ERROR: Invalid pattern is specified in "path:pattern".
UnboundLocalError("cannot access local variable 'editor_paths' where it is not associated with a value")
Traceback (most recent call last):
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\core\repl.py", line 1410, in run_command
    response = method(obj, argument)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\core\repl.py", line 1350, in command_config
    file_editor(self.config.config_file)
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\core\editor.py", line 59, in file_editor
    command_parts = discover_editor()
                    ^^^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\core\editor.py", line 44, in discover_editor
    if editor_paths:
       ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'editor_paths' where it is not associated with a value
```

**Comment by thehunmonkgroup** [comment]
And you're sure you're using the feature branch?

It should have this code added to `editor.py`:

https://github.com/llm-workflow-engine/llm-workflow-engine/blob/windows-editor-discovery/lwe/core/editor.py#L31-L33

If so, are you sure that's a valid path in your `EDITOR` variable? The checks in that code listed above are pretty simple -- is it a file and is it executable, so I don't understand why you're getting to that other branch of code if that is in fact a valid executable.

You'll probably need to put some additional debugging code in `editor.py` to see what check is failing.

**Comment by johnd0e** [comment]
The problem was due quotes:
`set EDITOR="C:\Users\johnd0e\AppData\Local\Programs\Microsoft VS Code\Code.exe"`

This works ok:
`set EDITOR=C:\Users\johnd0e\AppData\Local\Programs\Microsoft VS Code\Code.exe`

**Comment by thehunmonkgroup** [comment]
Great, that's progress!

Would you mind also testing the new code by setting `EDITOR` to *just* the name of a CLI editor in your `PATH`?

It would be nice to make sure that I didn't break the original editor detection code with this enhancement.

**Comment by johnd0e** [comment]
> Would you mind also testing the new code by setting EDITOR to just the name of a CLI editor in your PATH?

This also works without problem.

**Comment by thehunmonkgroup** [comment]
> This also works without problem.

Great, thanks for testing that. I've merged the features into the main branch.
