### ISSUE TITLE
How do i change the model?

### ISSUE THREAD

**Issue by frmsaul** [llm-workflow-engine/llm-workflow-engine#342]
The old chatgpt wrapper version had the ability to change the model you use by tying the command `/model gpt-4`. How do i do this in the current version.

I'm really struggling to understand the documentation. It's unclear to me what `presets` or `templates` are. Is there a simple way to change the model? 

```
frmsaul@gpt-3.5-turbo 2> /model gpt-4
/model gpt-4
Invalid key gpt-4.

Model Assistance Guide
(0.8/16384/34): default
frmsaul@gpt-3.5-turbo 2> /model model gpt-4
/model model gpt-4
Invalid key model.

Model Assistance Guide
(0.8/16384/34): default
```

These both fail.

**Comment by frmsaul** [comment]
Ok looks like it's something like: 

```
/model model_name gpt-4-turbo
```

I wish this appeared in a more prominent place in the documentation or in the help. This is what the help command looks like:

```
frmsaul@gpt-4-turbo 2> /help model 

View or set attributes on the current LLM model

Arguments:
    path: The attribute path to view or set
    value: The value to set the attribute to
    With no arguments, view current set model attributes

Examples:
    /model
    /model temperature
    /model temperature 1.1

Model Assistance Guide
```

**Comment by thehunmonkgroup** [comment]
This is an open source project, you are more than welcome to submit PRs to to improve the documentation. I will review any submitted PR.
