### ISSUE TITLE
Adding Ollama provider Python API

### ISSUE THREAD

**Issue by EstebanGameDevelopment** [llm-workflow-engine/llm-workflow-engine#344]
Hello,

I'm developing a personal project that involves working with a LLM with a large context length. I have previous successfully used this wrapper to interact with my OpenAI account, but since I need to do a lot of tests I have purchased a Jetson Orin AGX to have a local machine and use local models during development to reduce the cost.

So far, I've been able to change the provider to Ollama in LWE but I don't know what should I do in order to change the provider through the Python API. In the next image you can see how I successfully change to Ollama provider in LWE but when I run my Python app I cannot see the Ollama provider:

![HowToAddOllamaProviderPythonAPI](https://github.com/llm-workflow-engine/llm-workflow-engine/assets/32864363/e9e50bc4-689d-43f0-bd16-5e7eb62878c6)

This is the code of the application. So far I've successfully used with OpenAI with ChatGPT. The code allows me to manage the conversations and the only thing I need is to change the provider. I'm not a Python expert, so any help would be greatly appreciated.

[Python code of LLM conversation management Flask app](https://www.dropbox.com/scl/fi/qukqxme220q2izmggszkq/chatgpt_service.py?rlkey=ubv43tfdljfxfxcwh06th0lun&st=2l67b1b0&dl=0)

Thanks

**Comment by thehunmonkgroup** [comment]
https://github.com/llm-workflow-engine/llm-workflow-engine/blob/main/lwe/backends/api/repl.py contains the CLI functions for the API backend

https://github.com/llm-workflow-engine/llm-workflow-engine/blob/main/lwe/core/repl.py contains the general CLI functions.

Those are the places to look for understanding how to perform any operation in Python code that you can perform in the CLI.

You'll be looking for the `command_provider` method, which, at least right now, lives in these lines of code: https://github.com/llm-workflow-engine/llm-workflow-engine/blob/main/lwe/backends/api/repl.py#L701-L730

**Comment by EstebanGameDevelopment** [comment]
Thanks for the reply.

I must have not been able to explain myself properly. I only wanted to know how the existing method "set_provider" in the ApiBackend should work:

_Python code:_
```
llmAPI = ApiBackend()
llmAPI.set_provider('chat_ollama')
```
_Output:_ **ProviderManager - ERROR - Provider provider_chat_ollama not found in provider_plugins.**

so far when I list the available providers I only get this:

_Python code:_
```
llmAPI = ApiBackend()
providers_list = llmAPI.get_providers()
print("LLM PROVIDERS is {}".format(providers_list))
```
_Output:_ **LLM PROVIDERS is {'provider_chat_openai': <provider_chat_openai.ProviderChatOpenai object at 0xffffa9b89ae0>}**

The terminal shell commands are great and thanks to them I've been able to change the provider and set the local model I need, but what I need is to be able to use the existing ApiBackend's set_provider method in order to access to my local model through my Python code.

**Comment by thehunmonkgroup** [comment]
You're making an assumption about how the configuration is loaded. I'm guessing you have a `config.yaml`, and that's where you're enabling the `provider_chat_ollama`. The Python module doesn't load the config file by default.

Have a look at how the CLI handles setting up the config: https://github.com/llm-workflow-engine/llm-workflow-engine/blob/main/lwe/main.py#L133-L143

**Comment by EstebanGameDevelopment** [comment]
> You're making an assumption about how the configuration is loaded. I'm guessing you have a `config.yaml`, and that's where you're enabling the `provider_chat_ollama`. The Python module doesn't load the config file by default.

You are right. Python doesn't load that configuration. My question was how Python could load that configuration.

I'm sorry. I don't understand how I can replicate the part you show me with Python. I'll try my chances with a different solution. It's too bad because the only thing that I needed is for the existing ApiBackend's set_provider to work as intended.

**Comment by thehunmonkgroup** [comment]
```python
from lwe.core.config import Config
config = Config()
config.load_from_file()
llmAPI = ApiBackend(config)
```
If you have the config in the default location that should do it.
