### ISSUE TITLE
Does it support custom URLs for chat gpt ?

### ISSUE THREAD

**Issue by lmello** [llm-workflow-engine/llm-workflow-engine#348]
**Is your feature request related to a problem? Please describe.**
We have an internal proxy to chatgpt, I would like to provide the openai api hostname to use my internal proxy 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thehunmonkgroup** [comment]
Presets should support a parameter for a custom API base:

```
/model openai_api_base yourbaselocation
```

More information on presets here: https://llm-workflow-engine.readthedocs.io/en/latest/presets.html

**Comment by lmello** [comment]
Thank you
