### ISSUE TITLE
Parameters {'top_p'} should be specified explicitly

### ISSUE THREAD

**Issue by capybarahero** [llm-workflow-engine/llm-workflow-engine#349]
**Describe the bug**
I'm getting the error below after a clean install and using the existing default presets.

> ValidationError(model='CustomChatOpenAI', errors=[{'loc': ('__root__',), 'msg': "Parameters {'top_p'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.", 'type': 'value_error'}])

**To Reproduce**
1. Install from repo or locally.
2. Change the existing`/preset load <model>`.
3. You should see the error.

**Additional context**
This seems to be related to langchain and changes made to `langchain_openai` recently. I'll add more info soon.

**Comment by thehunmonkgroup** [comment]
Lord, they didn't even provide backwards compat, they just cowboy'd it :|

New release should fix this, although any existing installs will need to hand edit custom OpenAI presets they made.

If there's still an issue feel free to re-open.

Thanks for the report!

**Comment by thehunmonkgroup** [comment]
New release: https://github.com/llm-workflow-engine/llm-workflow-engine/releases/tag/v0.21.0
